version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ppid_garut
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C --auth-local=trust --auth-host=md5"
      PGUSER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ppid_garut"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    image: ${DOCKERHUB_USERNAME}/ppid-master:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD:-postgres123}@postgres:5432/ppid_garut?schema=public&connect_timeout=60&pool_timeout=60&sslmode=prefer"
      JWT_SECRET: ${JWT_SECRET:-ppid-garut-jwt-secret-2025}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000/api}
      NODE_ENV: production
      PORT: 3000
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/public/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data: