name: Build and Deploy to DockerHub

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/ppid-master:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/ppid-master:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Update deployment files
      run: |
        # Update docker-compose with actual username
        sed -i 's/${DOCKERHUB_USERNAME}/${{ secrets.DOCKERHUB_USERNAME }}/g' docker-compose.deploy.yml
        sed -i 's/your-dockerhub-username/${{ secrets.DOCKERHUB_USERNAME }}/g' deploy.sh
        
    - name: Create deployment package
      run: |
        tar -czf ppid-deployment-${{ github.sha }}.tar.gz docker-compose.deploy.yml deploy.sh
        echo "✅ Deployment package created for commit ${{ github.sha }}"